
# Environment variables to set in Travis:
# export AZURE_WA_USERNAME= Azure Git user
# export AZURE_WA_PASSWORD= Azure Git password (Make sure it's not in clear text)
# AZURE_WA_SITE = Azure site name


language: node_js
node_js:
  - "6"
script:
  - echo "Test your application here..."
deploy:
  - provider: azure_web_apps
    verbose: true
    slot: $AZURE_WA_SITE-prod # Will deploy to a slot called 'prod'
    on: master # From the master branch

  - provider: azure_web_apps
    verbose: true
    slot: $AZURE_WA_SITE-test
    on: test  

  - provider: azure_web_apps
    verbose: true
    slot: $AZURE_WA_SITE-dev
    on: dev
  

    